<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Jellyfin.Plugin.DD.Danmaku</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.DD.Danmaku</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="12.1.0" ExcludeAssets="runtime" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="Resources\ede.js">
      <LogicalName>Jellyfin.Plugin.DD.Danmaku.Resources.ede.js</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
